services:
  backend:
    build:
      context: ./backend
    ports:
      - "3001:3001"
    depends_on:
      - db
    volumes:
      - ./backend:/app
    env_file:
      - backend/.env

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    env_file:
      - frontend/.env
    
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pollnation_development
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data  # Named volume for database persistence

# Define the named volume with the local driver
volumes:
  pgdata:
    driver: local
